export function createDefaultSettings() {
  return {
    boxSize: "medium",
    checkColor: "#22c55e",
    rowCompleteBg: "#1f3b2e",
    accentColor: "#22c55e",
    bgColor: "#0b1020",
    bgGlow1: "#38bdf8",
    bgGlow2: "#22c55e",
    bgPattern: "none",
    bgPatternOpacity: 0.35,
    diceBg: "#f8fafc",
    dicePip: "#0f172a",
    diceBorder: "rgba(255,255,255,.12)",
    diceLocked: "rgba(34,197,94,.18)",
    dicePipLocked: "var(--accent)",
    btnPrimaryBg: "linear-gradient(180deg, rgba(34,197,94,1), rgba(16,185,129,1))",
    btnPrimaryText: "#07110b",
    btnPrimaryBorder: "rgba(0,0,0,.12)",
    btnPrimaryShadow: "0 10px 24px rgba(16,185,129,.25)",
    ringColorMode: "none",
    ringColors: null,
    themeKey: "Standard",
    buttonIcon: "",
    personalThemes: [],
    personalThemeId: null,
    filledRingColor: "#22c55e",
    checkShape: "circle",
    cellStyle: "ring",
    diceStyle: "classic",
    showDice: false,
    vibrateOnTurn: false,
    notifyTurn: true,
    notifyInvite: true,
    notifyBlitz: true,
  };
}
